name: Push Docker images

on:
  push:
    branches:
      - main
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello

    steps:
      - name: "hello"
        runs:
          using: "docker"
          image: "Dockerfile"
          args:
            - ${{ name }}
